FROM golang:latest
#Default GOPATH --> /go/src
WORKDIR $GOPATH/src/mypackage/myapp/
COPY . .
RUN go get . && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-w' -o web .
#ENTRYPOINT ["$GOPATH/src/mypackage/myapp/web"]
#Go programmed to listen on 5005 hence expose the port
EXPOSE 5005
CMD ["./web"]
#Image Size = 823MB
-------------------------------
#docker build -t goapp . -f mygodocker 
------------------------------------
# Test if working 
docker run --rm -it -p 5005:5005 goapp
#----------------------------------
#Copy go app  to PWD
#https://stackoverflow.com/questions/22049212/copying-files-from-docker-container-to-host
#docker create -ti --name dummy IMAGE_NAME bash
#docker cp dummy:/path/to/file /dest/to/file
#docker rm -fv dummy
#---------------------------------
#MINIMISE GO BUILD with multistage --
#https://www.cloudreach.com/blog/containerize-this-golang-dockerfiles/
#----------------------------------------------------
FROM golang as builder
#Default GOPATH --> /go/src
WORKDIR /go/src/mypackage/myapp/
COPY . .
RUN go get . && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-w' -o web .
FROM alpine
COPY --from=builder /go/src/mypackage/myapp/web /app/
WORKDIR /app
CMD ["./web"]
#Image Size = 13.8MB
#------------------------------------------------
#Minimize the entire runtime environment… build FROM scratch --
#https://www.cloudreach.com/blog/containerize-this-golang-dockerfiles/
#----------------------------------------------------
FROM golang as builder
#Default GOPATH --> /go/src
WORKDIR /go/src/mypackage/myapp/
COPY . .
RUN go get . && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-w' -o web .
FROM alpine
COPY --from=builder /go/src/mypackage/myapp/web /app/
COPY --from=builder /go/src/mypackage/myapp/index.html /app/
WORKDIR /app
CMD ["./web"]
#Image Size = 8.26MB
#-------------------------------------------------------
